name: Java CI/CD Pipeline

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  # JOB 1: ETAPA DE BUILD (COMPILAÇÃO)
  build:
    name: Build
    runs-on: ubuntu-latest

    # Define a pasta raiz do projeto Java para TODOS os passos deste job
    defaults:
      run:
        working-directory: ./tech-challenge-backend

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'tech-challenge-backend/pom.xml'

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar Aplicação e Gerar Pacote (sem rodar testes)
        run: ./mvnw clean package -DskipTests -B

      - name: Upload dos artefatos de build
        uses: actions/upload-artifact@v4
        with:
          name: target-build
          path: tech-challenge-backend/target/

  # JOB 2: ETAPA DE TESTES
  test:
    name: Testes
    runs-on: ubuntu-latest
    needs: build

    defaults:
      run:
        working-directory: ./tech-challenge-backend

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'tech-challenge-backend/pom.xml'

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Download dos artefatos de build
        uses: actions/download-artifact@v4
        with:
          name: target-build
          path: tech-challenge-backend/target/

      - name: Executar Testes Unitários
        run: ./mvnw test -Dgroups=unit -Dtest='!*Cucumber*' -B

      - name: Gerar Relatório JaCoCo
        if: always()
        run: ./mvnw jacoco:report -B